#!/usr/bin/env python
"""Generated by OpenClaw Materials Lab.

This script is an AiiDA submission scaffold. Review profile/code/pseudopotential settings before running.
"""
from pathlib import Path

STRUCTURE_PATH = Path('REPLACE_WITH_STRUCTURE')
MATERIAL_ID = 'mp-mock-hfo2'
CALCULATION_TYPE = 'dfpt-dielectric-tensor'
AIIDA_PROFILE = 'openclaw-demo'
AIIDA_CODE = 'qe-pw@localhost'


def main():
    print(f"Prepared AiiDA scaffold for {MATERIAL_ID}: {CALCULATION_TYPE}")
    print(f"profile={AIIDA_PROFILE} code={AIIDA_CODE} structure={STRUCTURE_PATH}")
    print("TODO: load aiida profile, create StructureData, configure builder, submit.")


if __name__ == "__main__":
    main()
